version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=local'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=localhost'
    ports:
      - 5432:5432
    command:
      - postgres
      - -c
      - log_statement=all
      - -c
      - log_destination=stderr
