# docker compose -f compose.yml -f compose.spring.yml up
version: '3'
services:
  spring:
    image: gradle:7.5.1-jdk17-alpine
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 5000:5000
      - 5005:5005
    environment:
      - POSTGRES_HOST=postgres
      - DB_USER=localhost
      - DB_PASS=password
      - DB_NAME=local
    depends_on:
      - postgres
    command: /bin/sh -c "gradle bootRun -PskipDownload=true --no-daemon"
